config/routes.rb
YourDict::Application.routes.draw do
  get "input/index"
  post "input/input"
  
  resources :words do
    member do
      get 'memorize' ,:to => 'words#memorize'
    end
    collection do
      get "not_memorize" , :to => "words#not_memorize"
      get "recent_memorize" , :to => "words#recent_memorize"
      get "many_count" , :to => "words#many_count"
      get "recent_add" , :to => "words#recent_add"
    end
  end

  root :to => 'home#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'basicuser' && password == 'basicpass'
  end
  mount Sidekiq::Web => '/sidekiq'
  
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :word
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
  devise :trackable, :omniauthable

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"]
      end
    end
  end


  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(username:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         #                          email:auth.info.email, #emailを取得したい場合は、migrationにemailを追加してください。
                         password:Devise.friendly_token[0,20]
                         )
    end
    user
  end


  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(username:auth.info.nickname,
                         provider:auth.provider,
                         uid:auth.uid,
                         #                          email:auth.extra.user_hash.email, #色々頑張りましたがtwitterではemail取得できません
                         password:Devise.friendly_token[0,20]
                         )
    end
    user
  end
  
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :user

  # 覚えていない
  scope :not_memorize , -> { where(:memorize_count => 0).order("updated_at") }
  # 覚えた
  scope :memorize , -> { where("memorize_count > 0").order("updated_at DESC") }
    
  # 最近覚えた
  scope :recent_memorize , -> { where("last_memorize_date > ?", 1.week.ago).order("updated_at DESC") }
  # 最近追加
  scope :recent_add , -> { order("created_at DESC") }
  # 出現回数順
  scope :many_count , -> { order("count DESC") }
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  protected
  def authenticate_user!
    session[:user_return_to] = env['PATH_INFO']
    redirect_to user_omniauth_authorize_path(:facebook) unless user_signed_in?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/input_controller.rb
class InputController < ApplicationController
  before_filter :authenticate_user!
  # get index
  def index
  end

  # post input
  def input
    string = params[:string]
    TranslateWorker.perform_async(string,current_user.id)
    #render :text => params.to_yaml
    #render :text => current_user.id
    redirect_to root_path , :flash => {:notice => '翻訳処理を開始しました。'}
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Twitter"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /words
  # GET /words.json
  def index
    @words = current_user.word.paginate(:page => params[:page], :per_page => 100)
  end
  
  def not_memorize
    @words = current_user.word.not_memorize.paginate(:page => params[:page], :per_page => 100)
    render "index"
  end
  
  def recent_memorize
    @words = current_user.word.memorize.recent_memorize.paginate(:page => params[:page], :per_page => 100)
    render "index"
  end
  
  def many_count
    @words = current_user.word.many_count.paginate(:page => params[:page], :per_page => 100)
    render "index"
  end
  
  def recent_add
    @words = current_user.word.recent_add.paginate(:page => params[:page], :per_page => 100)
    render "index"
  end
  

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = current_user.word.new
  end

  # GET /words/1/edit
  def edit
  end
  
  # GET /words/1/edit
  def memorize
    @word = Word.find(params[:id])
    @word.memorize_count += 1
    @word.last_memorize_date = Time.new
    @flg = false
    @flg = @word.save!
    #render :text => @word.to_yaml
    respond_to do |format|
      format.html { redirect_to words_url }
      format.js 
    end
  end

  # POST /words
  # POST /words.json
  def create
    @word = current_user.word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render action: 'show', status: :created, location: @word }
      else
        format.html { render action: 'new' }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:userid, :word, :translate, :count, :memorize_count, :last_memorize_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/input_helper.rb
module InputHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/home/index.html.erb
<h1>YourDict</h1>
<p>あなたの単語帳を作るサービスです。</p>
<p>Facebookかtwitterでログインして下さい。</p>
<p>新規単語登録から文書を登録して下さい。翻訳には少し時間がかかります。</p>
<p>翻訳されたあなたの単語帳は単語一覧から見ることができます。</p>
<p>&nbsp;</p>

app/views/input/index.html.erb
<h1><%= t('link.makenew') %></h1>
<p>文章をコピーアンドペーストして[登録]して下さい。単語に分割して辞書が作成されます。</p>
<%= form_tag(input_input_path,:method => :post) do %>
<%= text_area_tag 'string', '', :class => 'string_textarea' ,:style => 'width:100%' %>
<%= submit_tag "登録" ,:class => "btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "YourDict" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <span class="brand" href="#">YourDict</span>
          <div class="container nav-collapse">
            <% if user_signed_in? %>
              <ul class="nav">
                <li><%= link_to t('link.makenew'), input_index_path  %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">単語<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to t('link.listwords'), words_path  %></li>
                    <li><%= link_to "覚えていない単語", not_memorize_words_path %></li>
                    <li><%= link_to "最近覚えた単語", recent_memorize_words_path %></li>
                    <li><%= link_to "よく出る単語", many_count_words_path %></li>
                    <li><%= link_to "最近追加", recent_add_words_path %></li>
                  </ul>
                </li>
              </ul>
              <ul class="nav pull-right">
                <li><%= link_to t('link.logout'), destroy_user_session_path %></li>
              </ul>
              <% else %>
              <ul class="nav pull-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">ログイン<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to t('link.facebooklogin'), user_omniauth_authorize_path(:facebook) %></li>
                    <li class="divider"></li>
                    <li><%= link_to t('link.twitterlogin'), user_omniauth_authorize_path(:twitter)  %></li>
              </ul>
            </li>
            </ul>
                
              <% end %>
                
                
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; modeverv 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!--
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
-->  
  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :translate %><br>
    <%= f.text_field :translate %>
  </div>
<!--  
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="field">
    <%= f.label :memorize_count %><br>
    <%= f.number_field :memorize_count %>
  </div>
  <div class="field">
    <%= f.label :last_memorize_date %><br>
    <%= f.datetime_select :last_memorize_date %>
  </div>
-->  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>単語一覧</h1>
<%= will_paginate @words, renderer: BootstrapPagination::Rails ,:previous_label => t('views.input.prev_page'), :next_label => t('views.input.next_page')%>
<table class="table">
  <thead>
    <tr>
      <!--<th>Userid</th>-->
      <th><%= t('activerecord.attributes.word.word') %></th>
      <th><%= t('activerecord.attributes.word.translate') %></th>
      <th><%= t('activerecord.attributes.word.count') %></th>
      <th><%= t('activerecord.attributes.word.memorize') %></th>
      <th><%= t('activerecord.attributes.word.memorize_count') %></th>
      <th><%= t('activerecord.attributes.word.last_memorize_date') %></th>
      <!--<th></th>-->
      <th><%= t('activerecord.attributes.word.edit') %></th>
      <th><%= t('activerecord.attributes.word.delete') %></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr id='word_<%= word.id %>'>
        <!--<td><%= word.user_id %></td>-->
        <td><%= word.word %></td>
        <td><%= word.translate %></td>
        <td><%= word.count %></td>
        <td><%= link_to t('link.memorize'), memorize_word_path(word),:remote => true ,:class => "btn btn-mini" %></td>
        <td id='m_<%= word.id%>'><%= word.memorize_count %></td>
        <td id='md_<%= word.id%>'><%= l word.last_memorize_date , :format => "%m/%d" if !word.last_memorize_date.nil? %></td>
        <!--<td><%= link_to 'Show', word %></td>-->
        <td><%= link_to t('link.edit'), edit_word_path(word) ,:class => "btn btn-mini"%></td>
        <td><%= link_to t('link.delete'), word, method: :delete, data: { confirm: 'Are you sure?' } ,:class => "btn btn-mini"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @words, renderer: BootstrapPagination::Rails ,:previous_label => t('views.input.prev_page'), :next_label => t('views.input.next_page') %>
<br>

<%#= link_to 'New Word', new_word_path %>

app/views/words/memorize.js.erb
<% if @flg  %>
  var count = parseInt($('#m_<%= @word.id %>').html()) + 1;
  $('#m_<%= @word.id %>').html(count);
  $('#md_<%= @word.id %>').html('<%= l @word.last_memorize_date , :format => "%m/%d" if !@word.last_memorize_date.nil? %>');
<% else %>
  alert('更新失敗');
<% end %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>
<!--
<p>
  <strong>Userid:</strong>
  <%= @word.user_id %>
</p>
-->
<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<p>
  <strong>Translate:</strong>
  <%= @word.translate %>
</p>

<p>
  <strong>Count:</strong>
  <%= @word.count %>
</p>

<p>
  <strong>Memorize count:</strong>
  <%= @word.memorize_count %>
</p>

<p>
  <strong>Last memorize date:</strong>
  <%= @word.last_memorize_date %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>